In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.externals import joblib

In [2]:
poke = pd.read_csv('pokemon.csv')
poke['Type 2'].fillna(poke['Type 1'], inplace = True) #for every Pokemon with no Type 2, Type 2 is set to be the same with Type 1
poke.set_index('#', inplace = True) #without this, #800 would be lost
poke.head()
#joblib.dump(poke,'pokeStats.pkl')

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
4,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
5,Charmander,Fire,Fire,39,52,43,60,50,65,1,False

In [3]:
poke['Name'].fillna('Primeape', inplace = True)

In [4]:
pokeList = list(poke['Name'].values)
pokeDownloadNames = ','.join(pokeList)

In [5]:
type(poke.loc[298]['Type 1'])

str

In [6]:
sum(poke['Type 2'].isna())

0

In [7]:
combats = pd.read_csv('combats.csv')
combats.head()

   first  second  winner
0    266     298     298
1    702     701     701
2    191     668     668
3    237     683     683
4    151     231     151

In [8]:
sum(combats['second'].isna())

0

In [9]:
detailedCombats = combats
newColumns = ['Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Legendary']
#writing stats for first and second movers into the detailedCombats data frame
for num in ['first','second']:
    for col in newColumns:
        detailedCombats[num + col] = poke[col][combats[num]].reset_index()[col]
detailedCombats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 21 columns):
first              50000 non-null int64
second             50000 non-null int64
winner             50000 non-null int64
firstType 1        50000 non-null object
firstType 2        50000 non-null object
firstHP            50000 non-null int64
firstAttack        50000 non-null int64
firstDefense       50000 non-null int64
firstSp. Atk       50000 non-null int64
firstSp. Def       50000 non-null int64
firstSpeed         50000 non-null int64
firstLegendary     50000 non-null bool
secondType 1       50000 non-null object
secondType 2       50000 non-null object
secondHP           50000 non-null int64
secondAttack       50000 non-null int64
secondDefense      50000 non-null int64
secondSp. Atk      50000 non-null int64
secondSp. Def      50000 non-null int64
secondSpeed        50000 non-null int64
secondLegendary    50000 non-null bool
dtypes: bool(2), int64(15), object(4)
memory usage: 7.3+ MB

In [10]:
detailedCombats['Winner'] = (detailedCombats['winner']/detailedCombats['second'] == 1)
detailedCombats['Winner'] = detailedCombats['Winner'].astype('int64')
detailedCombats.head()

,first,second,winner,firstType 1,firstType 2,firstHP,firstAttack,firstDefense,firstSp. Atk,firstSp. Def,...,secondType 1,secondType 2,secondHP,secondAttack,secondDefense,secondSp. Atk,secondSp. Def,secondSpeed,secondLegendary,Winner
0,266,298,298,Rock,Ground,50,64,50,45,50,...,Grass,Dark,70,70,40,60,40,60,False,1
1,702,701,701,Grass,Fighting,91,90,72,90,129,...,Rock,Fighting,91,129,90,72,90,108,True,1
2,191,668,668,Fairy,Flying,55,40,85,80,105,...,Psychic,Psychic,75,75,75,125,95,40,False,1
3,237,683,683,Fire,Fire,40,40,40,70,40,...,Dragon,Dragon,77,120,90,60,90,48,False,1
4,151,231,151,Rock,Water,70,60,125,115,70,...,Bug,Rock,20,10,230,10,230,5,False,0

In [11]:
detailedCombats['firstLegendary'] = detailedCombats['firstLegendary'].astype('int64')
detailedCombats['secondLegendary'] = detailedCombats['secondLegendary'].astype('int64')
detailedCombats.head()

,first,second,winner,firstType 1,firstType 2,firstHP,firstAttack,firstDefense,firstSp. Atk,firstSp. Def,...,secondType 1,secondType 2,secondHP,secondAttack,secondDefense,secondSp. Atk,secondSp. Def,secondSpeed,secondLegendary,Winner
0,266,298,298,Rock,Ground,50,64,50,45,50,...,Grass,Dark,70,70,40,60,40,60,0,1
1,702,701,701,Grass,Fighting,91,90,72,90,129,...,Rock,Fighting,91,129,90,72,90,108,1,1
2,191,668,668,Fairy,Flying,55,40,85,80,105,...,Psychic,Psychic,75,75,75,125,95,40,0,1
3,237,683,683,Fire,Fire,40,40,40,70,40,...,Dragon,Dragon,77,120,90,60,90,48,0,1
4,151,231,151,Rock,Water,70,60,125,115,70,...,Bug,Rock,20,10,230,10,230,5,0,0

In [12]:
# typeChart = pd.read_csv('typeChart.csv')
# typeChart.set_index('Attacking', inplace = True)
# joblib.dump(typeChart,'typeChart.pkl')

In [13]:
typeChart = pd.read_csv('typeChart.csv', index_col = 'Attacking')
typeChart

,Normal,Fire,Water,Electric,Grass,Ice,Fighting,Poison,Ground,Flying,Psychic,Bug,Rock,Ghost,Dragon,Dark,Steel,Fairy
Attacking,,,,,,,,,,,,,,,,,,
Normal,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,0.0,1.0,1.0,0.5,1.0
Fire,1,0.5,0.5,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,0.5,1.0,0.5,1.0,2.0,1.0
Water,1,2.0,0.5,1.0,0.5,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,0.5,1.0,1.0,1.0
Electric,1,1.0,2.0,0.5,0.5,1.0,1.0,1.0,0.0,2.0,1.0,1.0,1.0,1.0,0.5,1.0,1.0,1.0
Grass,1,0.5,2.0,1.0,0.5,1.0,1.0,0.5,2.0,0.5,1.0,0.5,2.0,1.0,0.5,1.0,0.5,1.0
Ice,1,0.5,0.5,1.0,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,0.5,1.0
Fighting,2,1.0,1.0,1.0,1.0,2.0,1.0,0.5,1.0,0.5,0.5,0.5,2.0,0.0,1.0,2.0,2.0,0.5
Poison,1,1.0,1.0,1.0,2.0,1.0,1.0,0.5,0.5,1.0,1.0,1.0,0.5,0.5,1.0,1.0,0.0,2.0
Ground,1,2.0,1.0,2.0,0.5,1.0,1.0,2.0,1.0,0.0,1.0,0.5,2.0,1.0,1.0,1.0,2.0,1.0
Flying,1,1.0,1.0,0.5,2.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,0.5,1.0,1.0,1.0,0.5,1.0
Psychic,1,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,0.5,1.0,1.0,1.0,1.0,0.0,0.5,1.0
Bug,1,0.5,1.0,1.0,2.0,1.0,0.5,0.5,1.0,0.5,2.0,1.0,1.0,0.5,1.0,2.0,0.5,0.5
Rock,1,2.0,1.0,1.0,1.0,2.0,0.5,1.0,0.5,2.0,1.0,2.0,1.0,1.0,1.0,1.0,0.5,1.0
Ghost,0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,0.5,1.0,1.0
Dragon,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,0.5,0.0
Dark,1,1.0,1.0,1.0,1.0,1.0,0.5,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,0.5,1.0,0.5
Steel,1,0.5,0.5,0.5,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,0.5,2.0
Fairy,1,0.5,1.0,1.0,1.0,1.0,2.0,0.5,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,0.5,1.0

In [14]:
first = 'Rock'
second = 'Water'
typeChart[first][second]

2.0

In [15]:
def getTypeMatch(df):
    firstType1 = df['firstType 1']
    firstType2 = df['firstType 2']
    secondType1 = df['secondType 1']
    secondType2 = df['secondType 2']
    typeMatch = typeChart[secondType1][firstType1] * typeChart[secondType2][firstType2] * typeChart[secondType2][firstType1] * typeChart[secondType1][firstType2]
    return typeMatch
joblib.dump(getTypeMatch,'getTypeMatch.pkl')

['getTypeMatch.pkl']

In [16]:
test = detailedCombats
test['typeMatch'] = test.apply(lambda df: getTypeMatch(df), axis = 1)
test.head()

,first,second,winner,firstType 1,firstType 2,firstHP,firstAttack,firstDefense,firstSp. Atk,firstSp. Def,...,secondType 2,secondHP,secondAttack,secondDefense,secondSp. Atk,secondSp. Def,secondSpeed,secondLegendary,Winner,typeMatch
0,266,298,298,Rock,Ground,50,64,50,45,50,...,Dark,70,70,40,60,40,60,0,1,0.5000
1,702,701,701,Grass,Fighting,91,90,72,90,129,...,Fighting,91,129,90,72,90,108,1,1,4.0000
2,191,668,668,Fairy,Flying,55,40,85,80,105,...,Psychic,75,75,75,125,95,40,0,1,1.0000
3,237,683,683,Fire,Fire,40,40,40,70,40,...,Dragon,77,120,90,60,90,48,0,1,0.0625
4,151,231,151,Rock,Water,70,60,125,115,70,...,Rock,20,10,230,10,230,5,0,0,4.0000

In [17]:
test.columns

Index(['first', 'second', 'winner', 'firstType 1', 'firstType 2', 'firstHP',
       'firstAttack', 'firstDefense', 'firstSp. Atk', 'firstSp. Def',
       'firstSpeed', 'firstLegendary', 'secondType 1', 'secondType 2',
       'secondHP', 'secondAttack', 'secondDefense', 'secondSp. Atk',
       'secondSp. Def', 'secondSpeed', 'secondLegendary', 'Winner',
       'typeMatch'],
      dtype='object')

In [18]:
from sklearn.model_selection import cross_val_score
X = test[['firstHP',
       'firstAttack', 'firstDefense', 'firstSp. Atk', 'firstSp. Def',
       'firstSpeed', 'firstLegendary',
       'secondHP', 'secondAttack', 'secondDefense', 'secondSp. Atk',
       'secondSp. Def', 'secondSpeed', 'secondLegendary', 'typeMatch']]
X = X.iloc[:35000]
y = test['Winner']
y = y.iloc[:35000]

In [19]:
from sklearn.ensemble import RandomForestClassifier
pokeForest = RandomForestClassifier()
forestScores = cross_val_score(pokeForest, X, y, cv = 10, scoring = 'accuracy')
forestScores.mean()

0.9358573846064339

In [20]:
pokeForest.fit(X,y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [21]:

joblib.dump(pokeForest, 'pokeModel.pkl')

['pokeModel.pkl']

In [22]:
pd.__version__

'0.22.0'

In [23]:
pokeStats = poke
firstType1 = pokeStats[pokeStats['Name'] == 'Larvitar']['Type 1']
firstType2 = pokeStats[pokeStats['Name'] == 'Larvitar']['Type 2']
secondType1 = pokeStats[pokeStats['Name'] == 'Nuzleaf']['Type 1']
secondType2 = pokeStats[pokeStats['Name'] == 'Nuzleaf']['Type 2']
type(typeChart.loc[firstType1][secondType1].T.squeeze())

numpy.float64

In [24]:
type(test['firstHP'])

pandas.core.series.Series

In [25]:
firstHP = pokeStats[pokeStats['Name'] == 'Larvitar']['HP']
firstHP

#
266    50
Name: HP, dtype: int64

In [26]:
poke.head()

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
4,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
5,Charmander,Fire,Fire,39,52,43,60,50,65,1,False

In [27]:
pokeList = poke['Name'].values
pokeList

array(['Bulbasaur', 'Ivysaur', 'Venusaur', 'Mega Venusaur', 'Charmander',
       'Charmeleon', 'Charizard', 'Mega Charizard X', 'Mega Charizard Y',
       'Squirtle', 'Wartortle', 'Blastoise', 'Mega Blastoise', 'Caterpie',
       'Metapod', 'Butterfree', 'Weedle', 'Kakuna', 'Beedrill',
       'Mega Beedrill', 'Pidgey', 'Pidgeotto', 'Pidgeot', 'Mega Pidgeot',
       'Rattata', 'Raticate', 'Spearow', 'Fearow', 'Ekans', 'Arbok',
       'Pikachu', 'Raichu', 'Sandshrew', 'Sandslash', 'Nidoran♀',
       'Nidorina', 'Nidoqueen', 'Nidoran♂', 'Nidorino', 'Nidoking',
       'Clefairy', 'Clefable', 'Vulpix', 'Ninetales', 'Jigglypuff',
       'Wigglytuff', 'Zubat', 'Golbat', 'Oddish', 'Gloom', 'Vileplume',
       'Paras', 'Parasect', 'Venonat', 'Venomoth', 'Diglett', 'Dugtrio',
       'Meowth', 'Persian', 'Psyduck', 'Golduck', 'Mankey', 'Primeape',
       'Growlithe', 'Arcanine', 'Poliwag', 'Poliwhirl', 'Poliwrath',
       'Abra', 'Kadabra', 'Alakazam', 'Mega Alakazam', 'Machop',
       'Machoke', 'Machamp', 'Bellsprout', 'Weepinbell', 'Victreebel',
       'Tentacool', 'Tentacruel', 'Geodude', 'Graveler', 'Golem',
       'Ponyta', 'Rapidash', 'Slowpoke', 'Slowbro', 'Mega Slowbro',
       'Magnemite', 'Magneton', "Farfetch'd", 'Doduo', 'Dodrio', 'Seel',
       'Dewgong', 'Grimer', 'Muk', 'Shellder', 'Cloyster', 'Gastly',
       'Haunter', 'Gengar', 'Mega Gengar', 'Onix', 'Drowzee', 'Hypno',
       'Krabby', 'Kingler', 'Voltorb', 'Electrode', 'Exeggcute',
       'Exeggutor', 'Cubone', 'Marowak', 'Hitmonlee', 'Hitmonchan',
       'Lickitung', 'Koffing', 'Weezing', 'Rhyhorn', 'Rhydon', 'Chansey',
       'Tangela', 'Kangaskhan', 'Mega Kangaskhan', 'Horsea', 'Seadra',
       'Goldeen', 'Seaking', 'Staryu', 'Starmie', 'MrMime', 'Scyther',
       'Jynx', 'Electabuzz', 'Magmar', 'Pinsir', 'Mega Pinsir', 'Tauros',
       'Magikarp', 'Gyarados', 'Mega Gyarados', 'Lapras', 'Ditto',
       'Eevee', 'Vaporeon', 'Jolteon', 'Flareon', 'Porygon', 'Omanyte',
       'Omastar', 'Kabuto', 'Kabutops', 'Aerodactyl', 'Mega Aerodactyl',
       'Snorlax', 'Articuno', 'Zapdos', 'Moltres', 'Dratini', 'Dragonair',
       'Dragonite', 'Mewtwo', 'Mega Mewtwo X', 'Mega Mewtwo Y', 'Mew',
       'Chikorita', 'Bayleef', 'Meganium', 'Cyndaquil', 'Quilava',
       'Typhlosion', 'Totodile', 'Croconaw', 'Feraligatr', 'Sentret',
       'Furret', 'Hoothoot', 'Noctowl', 'Ledyba', 'Ledian', 'Spinarak',
       'Ariados', 'Crobat', 'Chinchou', 'Lanturn', 'Pichu', 'Cleffa',
       'Igglybuff', 'Togepi', 'Togetic', 'Natu', 'Xatu', 'Mareep',
       'Flaaffy', 'Ampharos', 'Mega Ampharos', 'Bellossom', 'Marill',
       'Azumarill', 'Sudowoodo', 'Politoed', 'Hoppip', 'Skiploom',
       'Jumpluff', 'Aipom', 'Sunkern', 'Sunflora', 'Yanma', 'Wooper',
       'Quagsire', 'Espeon', 'Umbreon', 'Murkrow', 'Slowking',
       'Misdreavus', 'Unown', 'Wobbuffet', 'Girafarig', 'Pineco',
       'Forretress', 'Dunsparce', 'Gligar', 'Steelix', 'Mega Steelix',
       'Snubbull', 'Granbull', 'Qwilfish', 'Scizor', 'Mega Scizor',
       'Shuckle', 'Heracross', 'Mega Heracross', 'Sneasel', 'Teddiursa',
       'Ursaring', 'Slugma', 'Magcargo', 'Swinub', 'Piloswine', 'Corsola',
       'Remoraid', 'Octillery', 'Delibird', 'Mantine', 'Skarmory',
       'Houndour', 'Houndoom', 'Mega Houndoom', 'Kingdra', 'Phanpy',
       'Donphan', 'Porygon2', 'Stantler', 'Smeargle', 'Tyrogue',
       'Hitmontop', 'Smoochum', 'Elekid', 'Magby', 'Miltank', 'Blissey',
       'Raikou', 'Entei', 'Suicune', 'Larvitar', 'Pupitar', 'Tyranitar',
       'Mega Tyranitar', 'Lugia', 'Ho-oh', 'Celebi', 'Treecko', 'Grovyle',
       'Sceptile', 'Mega Sceptile', 'Torchic', 'Combusken', 'Blaziken',
       'Mega Blaziken', 'Mudkip', 'Marshtomp', 'Swampert',
       'Mega Swampert', 'Poochyena', 'Mightyena', 'Zigzagoon', 'Linoone',
       'Wurmple', 'Silcoon', 'Beautifly', 'Cascoon', 'Dustox', 'Lotad',
       'Lombre', 'Ludicolo', 'Seedot', 'Nuzleaf', 'Shiftry', 'Taillow',
       'Swellow', 'Wingull', 'Pelipper', 'Ralts', 'Kirlia', 'Gardevoir',
       'Mega Gardevoir', 'Surskit', 'Masquerain', 'Shroomish', 'Breloom',
       'Slakoth', 'Vigoroth', 'Slaking', 'Nincada', 'Ninjask', 'Shedinja',
       'Whismur', 'Loudred', 'Exploud', 'Makuhita', 'Hariyama', 'Azurill',
       'Nosepass', 'Skitty', 'Delcatty', 'Sableye', 'Mega Sableye',
       'Mawile', 'Mega Mawile', 'Aron', 'Lairon', 'Aggron', 'Mega Aggron',
       'Meditite', 'Medicham', 'Mega Medicham', 'Electrike', 'Manectric',
       'Mega Manectric', 'Plusle', 'Minun', 'Volbeat', 'Illumise',
       'Roselia', 'Gulpin', 'Swalot', 'Carvanha', 'Sharpedo',
       'Mega Sharpedo', 'Wailmer', 'Wailord', 'Numel', 'Camerupt',
       'Mega Camerupt', 'Torkoal', 'Spoink', 'Grumpig', 'Spinda',
       'Trapinch', 'Vibrava', 'Flygon', 'Cacnea', 'Cacturne', 'Swablu',
       'Altaria', 'Mega Altaria', 'Zangoose', 'Seviper', 'Lunatone',
       'Solrock', 'Barboach', 'Whiscash', 'Corphish', 'Crawdaunt',
       'Baltoy', 'Claydol', 'Lileep', 'Cradily', 'Anorith', 'Armaldo',
       'Feebas', 'Milotic', 'Castform', 'Kecleon', 'Shuppet', 'Banette',
       'Mega Banette', 'Duskull', 'Dusclops', 'Tropius', 'Chimecho',
       'Absol', 'Mega Absol', 'Wynaut', 'Snorunt', 'Glalie',
       'Mega Glalie', 'Spheal', 'Sealeo', 'Walrein', 'Clamperl',
       'Huntail', 'Gorebyss', 'Relicanth', 'Luvdisc', 'Bagon', 'Shelgon',
       'Salamence', 'Mega Salamence', 'Beldum', 'Metang', 'Metagross',
       'Mega Metagross', 'Regirock', 'Regice', 'Registeel', 'Latias',
       'Mega Latias', 'Latios', 'Mega Latios', 'Kyogre', 'Primal Kyogre',
       'Groudon', 'Primal Groudon', 'Rayquaza', 'Mega Rayquaza',
       'Jirachi', 'Deoxys Normal Forme', 'Deoxys Attack Forme',
       'Deoxys Defense Forme', 'Deoxys Speed Forme', 'Turtwig', 'Grotle',
       'Torterra', 'Chimchar', 'Monferno', 'Infernape', 'Piplup',
       'Prinplup', 'Empoleon', 'Starly', 'Staravia', 'Staraptor',
       'Bidoof', 'Bibarel', 'Kricketot', 'Kricketune', 'Shinx', 'Luxio',
       'Luxray', 'Budew', 'Roserade', 'Cranidos', 'Rampardos', 'Shieldon',
       'Bastiodon', 'Burmy', 'Wormadam Plant Cloak',
       'Wormadam Sandy Cloak', 'Wormadam Trash Cloak', 'Mothim', 'Combee',
       'Vespiquen', 'Pachirisu', 'Buizel', 'Floatzel', 'Cherubi',
       'Cherrim', 'Shellos', 'Gastrodon', 'Ambipom', 'Drifloon',
       'Drifblim', 'Buneary', 'Lopunny', 'Mega Lopunny', 'Mismagius',
       'Honchkrow', 'Glameow', 'Purugly', 'Chingling', 'Stunky',
       'Skuntank', 'Bronzor', 'Bronzong', 'Bonsly', 'MimeJr', 'Happiny',
       'Chatot', 'Spiritomb', 'Gible', 'Gabite', 'Garchomp',
       'Mega Garchomp', 'Munchlax', 'Riolu', 'Lucario', 'Mega Lucario',
       'Hippopotas', 'Hippowdon', 'Skorupi', 'Drapion', 'Croagunk',
       'Toxicroak', 'Carnivine', 'Finneon', 'Lumineon', 'Mantyke',
       'Snover', 'Abomasnow', 'Mega Abomasnow', 'Weavile', 'Magnezone',
       'Lickilicky', 'Rhyperior', 'Tangrowth', 'Electivire', 'Magmortar',
       'Togekiss', 'Yanmega', 'Leafeon', 'Glaceon', 'Gliscor',
       'Mamoswine', 'Porygon-Z', 'Gallade', 'Mega Gallade', 'Probopass',
       'Dusknoir', 'Froslass', 'Rotom', 'Heat Rotom', 'Wash Rotom',
       'Frost Rotom', 'Fan Rotom', 'Mow Rotom', 'Uxie', 'Mesprit',
       'Azelf', 'Dialga', 'Palkia', 'Heatran', 'Regigigas',
       'Giratina Altered Forme', 'Giratina Origin Forme', 'Cresselia',
       'Phione', 'Manaphy', 'Darkrai', 'Shaymin Land Forme',
       'Shaymin Sky Forme', 'Arceus', 'Victini', 'Snivy', 'Servine',
       'Serperior', 'Tepig', 'Pignite', 'Emboar', 'Oshawott', 'Dewott',
       'Samurott', 'Patrat', 'Watchog', 'Lillipup', 'Herdier',
       'Stoutland', 'Purrloin', 'Liepard', 'Pansage', 'Simisage',
       'Pansear', 'Simisear', 'Panpour', 'Simipour', 'Munna', 'Musharna',
       'Pidove', 'Tranquill', 'Unfezant', 'Blitzle', 'Zebstrika',
       'Roggenrola', 'Boldore', 'Gigalith', 'Woobat', 'Swoobat',
       'Drilbur', 'Excadrill', 'Audino', 'Mega Audino', 'Timburr',
       'Gurdurr', 'Conkeldurr', 'Tympole', 'Palpitoad', 'Seismitoad',
       'Throh', 'Sawk', 'Sewaddle', 'Swadloon', 'Leavanny', 'Venipede',
       'Whirlipede', 'Scolipede', 'Cottonee', 'Whimsicott', 'Petilil',
       'Lilligant', 'Basculin', 'Sandile', 'Krokorok', 'Krookodile',
       'Darumaka', 'Darmanitan Standard Mode', 'Darmanitan Zen Mode',
       'Maractus', 'Dwebble', 'Crustle', 'Scraggy', 'Scrafty', 'Sigilyph',
       'Yamask', 'Cofagrigus', 'Tirtouga', 'Carracosta', 'Archen',
       'Archeops', 'Trubbish', 'Garbodor', 'Zorua', 'Zoroark', 'Minccino',
       'Cinccino', 'Gothita', 'Gothorita', 'Gothitelle', 'Solosis',
       'Duosion', 'Reuniclus', 'Ducklett', 'Swanna', 'Vanillite',
       'Vanillish', 'Vanilluxe', 'Deerling', 'Sawsbuck', 'Emolga',
       'Karrablast', 'Escavalier', 'Foongus', 'Amoonguss', 'Frillish',
       'Jellicent', 'Alomomola', 'Joltik', 'Galvantula', 'Ferroseed',
       'Ferrothorn', 'Klink', 'Klang', 'Klinklang', 'Tynamo', 'Eelektrik',
       'Eelektross', 'Elgyem', 'Beheeyem', 'Litwick', 'Lampent',
       'Chandelure', 'Axew', 'Fraxure', 'Haxorus', 'Cubchoo', 'Beartic',
       'Cryogonal', 'Shelmet', 'Accelgor', 'Stunfisk', 'Mienfoo',
       'Mienshao', 'Druddigon', 'Golett', 'Golurk', 'Pawniard', 'Bisharp',
       'Bouffalant', 'Rufflet', 'Braviary', 'Vullaby', 'Mandibuzz',
       'Heatmor', 'Durant', 'Deino', 'Zweilous', 'Hydreigon', 'Larvesta',
       'Volcarona', 'Cobalion', 'Terrakion', 'Virizion',
       'Tornadus Incarnate Forme', 'Tornadus Therian Forme',
       'Thundurus Incarnate Forme', 'Thundurus Therian Forme', 'Reshiram',
       'Zekrom', 'Landorus Incarnate Forme', 'Landorus Therian Forme',
       'Kyurem', 'Black Kyurem', 'White Kyurem', 'Keldeo Ordinary Form',
       'Keldeo Resolute Form', 'Meloetta Aria Forme',
       'Meloetta Pirouette Forme', 'Genesect', 'Chespin', 'Quilladin',
       'Chesnaught', 'Fennekin', 'Braixen', 'Delphox', 'Froakie',
       'Frogadier', 'Greninja', 'Bunnelby', 'Diggersby', 'Fletchling',
       'Fletchinder', 'Talonflame', 'Scatterbug', 'Spewpa', 'Vivillon',
       'Litleo', 'Pyroar', 'Flabebe', 'Floette', 'Florges', 'Skiddo',
       'Gogoat', 'Pancham', 'Pangoro', 'Furfrou', 'Espurr',
       'Meowstic Male', 'Meowstic Female', 'Honedge', 'Doublade',
       'Aegislash Blade Forme', 'Aegislash Shield Forme', 'Spritzee',
       'Aromatisse', 'Swirlix', 'Slurpuff', 'Inkay', 'Malamar', 'Binacle',
       'Barbaracle', 'Skrelp', 'Dragalge', 'Clauncher', 'Clawitzer',
       'Helioptile', 'Heliolisk', 'Tyrunt', 'Tyrantrum', 'Amaura',
       'Aurorus', 'Sylveon', 'Hawlucha', 'Dedenne', 'Carbink', 'Goomy',
       'Sliggoo', 'Goodra', 'Klefki', 'Phantump', 'Trevenant',
       'Pumpkaboo Average Size', 'Pumpkaboo Small Size',
       'Pumpkaboo Large Size', 'Pumpkaboo Super Size',
       'Gourgeist Average Size', 'Gourgeist Small Size',
       'Gourgeist Large Size', 'Gourgeist Super Size', 'Bergmite',
       'Avalugg', 'Noibat', 'Noivern', 'Xerneas', 'Yveltal',
       'Zygarde Half Forme', 'Diancie', 'Mega Diancie', 'Hoopa Confined',
       'Hoopa Unbound', 'Volcanion'], dtype=object)

In [31]:
poke['Name'][poke['Name'].isna()] #used to be Primeape at #63

Series([], Name: Name, dtype: object)